Creatisa/Controllers/CapController.cs
using Creatisa.Data;
using Creatisa.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Creatisa.Identity;
namespace Creatisa.Controllers;

 public class CapController : Controller
    {
        private readonly ILogger<CapController> _logger;
        private readonly ApplicationDbContext _context;

        public CapController(ILogger<CapController> logger, ApplicationDbContext context)
        {
            _logger = logger;
            _context = context;
        }

        public IActionResult CapsList()
        {
            List<CapModel> list = _context.Caps.Select(c => new CapModel()
            {
                Id = c.Id,
                Name = c.Name,
                Color = c.Color,
                CapSize = c.CapSize,
                Price = c.Price,
                Type = c.Type,
                Material = c.Material,
                Quantity = c.Quantity
            }).ToList();
            return View(list);
        }

        public IActionResult CapsAdd(CapModel cap)
        {
            if (ModelState.IsValid)
            {
                Cap capInfo = new Cap()
                {
                    Id = Guid.NewGuid(),
                    Name = cap.Name,
                    Color = cap.Color,
                    CapSize = cap.CapSize,
                    Price = cap.Price,
                    Type = cap.Type,
                    Material = cap.Material,
                    Quantity = cap.Quantity
                };
                _context.Caps.Add(capInfo);
                _context.SaveChanges();
                return RedirectToAction("CapsList");
            }
            return View();
        }

        [HttpGet]
        public IActionResult CapsEdit(Guid Id)
        {
            Cap capToUpdate = _context.Caps.FirstOrDefault(c => c.Id == Id);
            if (capToUpdate == null)
            {
                return RedirectToAction("CapsList");
            }
            
            CapModel model = new CapModel()
            {
                Id = capToUpdate.Id,
                Name = capToUpdate.Name,
                Color = capToUpdate.Color,
                CapSize = capToUpdate.CapSize,
                Price = capToUpdate.Price,
                Type = capToUpdate.Type,
                Material = capToUpdate.Material,
                Quantity = capToUpdate.Quantity
            };
            return View(model);
        }

        [HttpPost]
        public IActionResult CapsEdit(CapModel model)
        {
            if (ModelState.IsValid)
            {
                Cap capToUpdate = _context.Caps.FirstOrDefault(c => c.Id == model.Id);
                if (capToUpdate == null)
                {
                    return RedirectToAction("CapsList");
                }

                capToUpdate.Name = model.Name;
                capToUpdate.Color = model.Color;
                capToUpdate.CapSize = model.CapSize;
                capToUpdate.Price = model.Price;
                capToUpdate.Type = model.Type;
                capToUpdate.Material = model.Material;
                capToUpdate.Quantity = model.Quantity;

                _context.Caps.Update(capToUpdate);
                _context.SaveChanges();

                return RedirectToAction("CapsList");
            }
            return View(model);
        }

        [HttpGet]
        public IActionResult CapsDelete(Guid Id)
        {
            Cap capToDelete = _context.Caps.FirstOrDefault(c => c.Id == Id);
            if (capToDelete == null)
            {
                return RedirectToAction("CapsList");
            }

            CapModel model = new CapModel()
            {
                Id = capToDelete.Id,
                Name = capToDelete.Name,
                Color = capToDelete.Color,
                CapSize = capToDelete.CapSize,
                Price = capToDelete.Price,
                Type = capToDelete.Type,
                Material = capToDelete.Material,
                Quantity = capToDelete.Quantity
            };
            return View(model);
        }

        [HttpPost]
        public IActionResult CapsDelete(CapModel model)
        {
            Cap capToDelete = _context.Caps.FirstOrDefault(c => c.Id == model.Id);
            if (capToDelete == null)
            {
                return RedirectToAction("CapsList");
            }

            _context.Caps.Remove(capToDelete);
            _context.SaveChanges();

            return RedirectToAction("CapsList");
        }
    }

Creatisa/Views/Cap/CapAdd.cshtml
@model CapModel
@{
    ViewData["Title"] = "Alta de Gorras";
}
<link rel="stylesheet" href="~/css/añadir.css">

<div asp-validation-summary="All" class="text-danger"></div>

<div class="container-addd">

    <div class="content-addd">
        <h1 class="">Alta de Gorras</h1>
    </div>

    <form asp-controller="Cap" asp-action="CapsAdd">
        <div class="mb-3">
            <label for="Name" class="form-label">Nombre</label>
            <input type="text" class="form-control" id="Name" name="Name" placeholder="Escriba el nombre de la gorra:" />
        </div>

        <div class="mb-3">
            <label for="Color" class="form-label">Color</label>
            <input type="text" class="form-control" id="Color" name="Color" placeholder="Escriba el color de la gorra:" />
        </div>

        <div class="mb-3">
            <label for="CapSize" class="form-label">Talla</label>
            <input type="text" class="form-control" id="CapSize" name="CapSize" placeholder="Escriba la talla de la gorra:" />
        </div>

        <div class="mb-3">
            <label for="Price" class="form-label">Precio</label>
            <input type="text" class="form-control" id="Price" name="Price" placeholder="Escriba el precio de la gorra:" />
        </div>

        <div class="mb-3">
            <label for="Type" class="form-label">Tipo</label>
            <input type="text" class="form-control" id="Type" name="Type" placeholder="Escriba el tipo de gorra:" />
        </div>

        <div class="mb-3">
            <label for="Material" class="form-label">Material</label>
            <input type="text" class="form-control" id="Material" name="Material" placeholder="Escriba el material de la gorra:" />
        </div>

        <div class="mb-3">
            <label for="Quantity" class="form-label">Cantidad</label>
            <input type="text" class="form-control" id="Quantity" name="Quantity" placeholder="Escriba la cantidad disponible:" />
        </div>

        <button type="submit" class="boton">Guardar</button>
        <button class="boton" asp-controller="Cap" asp-action="CapsList" class="btn btn-danger mb-3">Regresar</button>
    </form>
</div>

Creatisa/Views/Cap/CapDeleted.cshtml
@model CapModel

@{
    ViewData["Title"] = "Borrar la categoría de la Gorra";
}
<link rel="stylesheet" href="~/css/borrar.css">

<div class="container-borrar">
    <div class="mac">
        <img src="~/imgadmin/red.svg" alt="">
        <img src="~/imgadmin/orange.svg" alt="">
        <img src="~/imgadmin/green.svg" alt="">
    </div>
    <div class="content-borrar">
        <h1>¿Estás seguro de que deseas borrar la gorra @Model.Name ?</h1>
    </div>

    <form asp-controller="Cap" asp-action="CapsDeleted">
        <button type="submit" class="boton">Borrar</button>
        <button class="boton" asp-action="CapsList" asp-controller="Cap">Cancelar</button>
    </form>
</div>

Creatisa/Views/Cap/CapEdit.cshtml
@model CapModel

@{
    ViewData["Title"] = "Editar la Gorra";
}
<link rel="stylesheet" href="~/css/editar.css">

<div class="alertas">
    <div asp-validation-summary="All" class="text-danger"></div>
</div>

<form class="formu" asp-action="CapsEdit" asp-controller="Cap">
    <input type="hidden" asp-for="Id">

    <div class="container-editar">
      <h1 class="">Editar Gorra @Model.Name</h1>
    </div>

    <div class="mb-3">
        <label asp-for="Name">Nombre de la Gorra</label>
        <input type="text" class="form-control" asp-for="Name" placeholder="Nombre de la Gorra">
    </div>
    
    <div class="mb-3">
        <label asp-for="Color">Color</label>
        <input type="text" class="form-control" asp-for="Color" placeholder="Color de la Gorra">
    </div>

    <div class="mb-3">
        <label asp-for="CapSize">Tamaño</label>
        <input type="text" class="form-control" asp-for="CapSize" placeholder="Tamaño de la Gorra">
    </div>

    <div class="mb-3">
        <label asp-for="Price">Precio</label>
        <input type="text" class="form-control" asp-for="Price" placeholder="Precio de la Gorra">
    </div>

    <div class="mb-3">
        <label asp-for="Type">Tipo</label>
        <input type="text" class="form-control" asp-for="Type" placeholder="Tipo de Gorra">
    </div>

    <div class="mb-3">
        <label asp-for="Material">Material</label>
        <input type="text" class="form-control" asp-for="Material" placeholder="Material de la Gorra">
    </div>

    <div class="mb-3">
        <label asp-for="Quantity">Cantidad</label>
        <input type="number" class="form-control" asp-for="Quantity" placeholder="Cantidad disponible">
    </div>

    <button class="boton">Guardar</button>
    <button class="boton mb-3" asp-action="CapsList" asp-controller="Cap">Regresar</button>
</form>

Creatisa/Views/Cap/CapList.cshtml
@model List<CapModel> 

@{
    ViewData["Title"] = "Listado de Gorras:";
    int Id = 0;
}
<link rel="stylesheet" href="~/css/views.css">

<div class="container-tablas">
    <div class="tabla-titul">
        <h1>Listado de Gorras</h1>
        <a asp-controller="Cap" asp-action="CapsAdd">+ Añadir</a>
    </div>

    <table class="tablass table table-borderless table-striped table-hover">  
        <thead>
            <tr>
                <th scope="col">Acciones</th>
                <th scope="col">ID</th>
                <th scope="col">Nombre</th>
                <th scope="col">Color</th>
                <th scope="col">Tamaño</th>
                <th scope="col">Precio</th>
                <th scope="col">Tipo</th>
                <th scope="col">Material</th>
                <th scope="col">Cantidad</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var cap in Model)
            {
                Id++;
                <tr>
                    <td>
                        <a class="btn" asp-controller="Cap" asp-action="CapsEdit" asp-route-id="@cap.Id">
                            <img class="editarr" src="~/imgadmin/edit.svg" alt="Editar">
                        </a>
                        <a class="btn" asp-controller="Cap" asp-action="CapsDeleted" asp-route-id="@cap.Id">
                            <img class="editarr" src="~/imgadmin/basura.svg" alt="Eliminar">
                        </a>
                    </td>
                    <td> @Id </td>
                    <td> @cap.Name</td>
                    <td> @cap.Color</td>
                    <td> @cap.CapSize</td>
                    <td> @cap.Price</td>
                    <td> @cap.Type</td>
                    <td> @cap.Material</td>
                    <td> @cap.Quantity</td>
                </tr>
            }
        </tbody>
    </table>
</div>