Creatisa/Controllers/ShirtController.cs
using Creatisa.Data;
using Creatisa.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Creatisa.Identity;

namespace Creatisa.Controllers;

public class ShirtController : Controller
{
    private readonly ILogger<ShirtController> _logger;
    private readonly ApplicationDbContext _context;

    public ShirtController(ILogger<ShirtController> logger, ApplicationDbContext context)
    {
        _logger = logger;
        _context = context;
    }

    public IActionResult ShirtsList()
    {
        List<ShirtModel> list = _context.Shirts.Select(s => new ShirtModel()
        {
            Id = s.Id,
            Name = s.Name,
            Color = s.Color,
            ShirtSize = s.ShirtSize,
            Price = s.Price,
            Type = s.Type,
            Material = s.Material,
            Quantity = s.Quantity
        }).ToList();
        return View(list);
    }

    public IActionResult ShirtsAdd(ShirtModel shirt)
    {
        if (ModelState.IsValid)
        {
            Shirt shirtInfo = new Shirt()
            {
                Id = Guid.NewGuid(),
                Name = shirt.Name,
                Color = shirt.Color,
                ShirtSize = shirt.ShirtSize,
                Price = shirt.Price,
                Type = shirt.Type,
                Material = shirt.Material,
                Quantity = shirt.Quantity
            };
            _context.Shirts.Add(shirtInfo);
            _context.SaveChanges();
            return RedirectToAction("ShirtsList");
        }
        return View();
    }

    [HttpGet]
    public IActionResult ShirtsEdit(Guid Id)
    {
        Shirt shirtToUpdate = _context.Shirts.FirstOrDefault(s => s.Id == Id);
        if (shirtToUpdate == null)
        {
            return RedirectToAction("ShirtsList");
        }

        ShirtModel model = new ShirtModel()
        {
            Id = shirtToUpdate.Id,
            Name = shirtToUpdate.Name,
            Color = shirtToUpdate.Color,
            ShirtSize = shirtToUpdate.ShirtSize,
            Price = shirtToUpdate.Price,
            Type = shirtToUpdate.Type,
            Material = shirtToUpdate.Material,
            Quantity = shirtToUpdate.Quantity
        };
        return View(model);
    }

    [HttpPost]
    public IActionResult ShirtsEdit(ShirtModel model)
    {
        if (ModelState.IsValid)
        {
            Shirt shirtToUpdate = _context.Shirts.FirstOrDefault(s => s.Id == model.Id);
            if (shirtToUpdate == null)
            {
                return RedirectToAction("ShirtsList");
            }

            shirtToUpdate.Name = model.Name;
            shirtToUpdate.Color = model.Color;
            shirtToUpdate.ShirtSize = model.ShirtSize;
            shirtToUpdate.Price = model.Price;
            shirtToUpdate.Type = model.Type;
            shirtToUpdate.Material = model.Material;
            shirtToUpdate.Quantity = model.Quantity;

            _context.Shirts.Update(shirtToUpdate);
            _context.SaveChanges();

            return RedirectToAction("ShirtsList");
        }
        return View(model);
    }

    [HttpGet]
    public IActionResult ShirtsDelete(Guid Id)
    {
        Shirt shirtToDelete = _context.Shirts.FirstOrDefault(s => s.Id == Id);
        if (shirtToDelete == null)
        {
            return RedirectToAction("ShirtsList");
        }

        ShirtModel model = new ShirtModel()
        {
            Id = shirtToDelete.Id,
            Name = shirtToDelete.Name,
            Color = shirtToDelete.Color,
            ShirtSize = shirtToDelete.ShirtSize,
            Price = shirtToDelete.Price,
            Type = shirtToDelete.Type,
            Material = shirtToDelete.Material,
            Quantity = shirtToDelete.Quantity
        };
        return View(model);
    }

    [HttpPost]
    public IActionResult ShirtsDelete(ShirtModel model)
    {
        Shirt shirtToDelete = _context.Shirts.FirstOrDefault(s => s.Id == model.Id);
        if (shirtToDelete == null)
        {
            return RedirectToAction("ShirtsList");
        }

        _context.Shirts.Remove(shirtToDelete);
        _context.SaveChanges();

        return RedirectToAction("ShirtsList");
    }
}

Creatisa/Views/Shirt/ShirtAdd.cshtml
@model ShirtModel

@{
    ViewData["Title"] = "Alta de Camiseta";
}
<link rel="stylesheet" href="~/css/añadir.css">

<div asp-validation-summary="All" class="text-danger"></div>

<div class="container-addd">
    <div class="content-addd">
        <h1>Alta de Camiseta</h1>
    </div>

    <form asp-controller="Shirt" asp-action="ShirtsAdd">
        <div class="mb-3">
            <label for="Name" class="form-label">Nombre</label>
            <input type="text" class="form-control" id="Name" name="Name" placeholder="Escriba el nombre de la camiseta" required />
        </div>
        <div class="mb-3">
            <label for="Color" class="form-label">Color</label>
            <input type="text" class="form-control" id="Color" name="Color" placeholder="Escriba el color de la camiseta" required />
        </div>
        <div class="mb-3">
            <label for="ShirtSize" class="form-label">Tamaño</label>
            <input type="text" class="form-control" id="ShirtSize" name="ShirtSize" placeholder="Escriba el tamaño de la camiseta" required />
        </div>
        <div class="mb-3">
            <label for="Price" class="form-label">Precio</label>
            <input type="number" class="form-control" id="Price" name="Price" placeholder="Escriba el precio de la camiseta" required />
        </div>
        <div class="mb-3">
            <label for="Type" class="form-label">Tipo</label>
            <input type="text" class="form-control" id="Type" name="Type" placeholder="Escriba el tipo de la camiseta" required />
        </div>
        <div class="mb-3">
            <label for="Material" class="form-label">Material</label>
            <input type="text" class="form-control" id="Material" name="Material" placeholder="Escriba el material de la camiseta" />
        </div>
        <div class="mb-3">
            <label for="Quantity" class="form-label">Cantidad</label>
            <input type="number" class="form-control" id="Quantity" name="Quantity" placeholder="Escriba la cantidad de camisetas" required />
        </div>
        <button type="submit" class="boton">Guardar</button>
        <button class="boton" asp-controller="Shirt" asp-action="ShirtsList" class="btn btn-danger mb-3">Regresar</button>
    </form>
</div>

Creatisa/Views/Shirt/ShirtDeleted.cshtml
@model ShirtModel

@{
    ViewData["Title"] = "Eliminar Camiseta";
}
<link rel="stylesheet" href="~/css/borrar.css">

<div class="container-borrar">
    <div class="mac">
        <img src="~/imgadmin/red.svg" alt="">
        <img src="~/imgadmin/orange.svg" alt="">
        <img src="~/imgadmin/green.svg" alt="">
    </div>
    <div class="content-borrar">
        <h1>¿Estás seguro de que deseas eliminar la camiseta @Model.Name?</h1>
    </div>

    <form asp-controller="Shirt" asp-action="ShirtsDeleted">
        <button type="submit" class="boton">Eliminar</button>
        <button class="boton" asp-action="ShirtsList" asp-controller="Shirt">Cancelar</button>
    </form>
</div>

Creatisa/Views/Shirt/ShirtEdit.cshtml
@model ShirtModel

@{
    ViewData["Title"] = "Editar Camiseta";
}
<link rel="stylesheet" href="~/css/editar.css">

<div class="alertas">
    <div asp-validation-summary="All" class="text-danger"></div>
</div>

<form class="formu" asp-action="ShirtsEdit" asp-controller="Shirt">
    <input type="hidden" asp-for="Id">

    <div class="container-editar">
        <h1>Editar Camiseta @Model.Name</h1>
    </div>

    <div class="mb-3">
        <label asp-for="Name">Nombre de la Camiseta</label>
        <input type="text" class="form-control" asp-for="Name" placeholder="Nombre de la Camiseta" required />
    </div>
    <div class="mb-3">
        <label asp-for="Color">Color</label>
        <input type="text" class="form-control" asp-for="Color" placeholder="Color de la Camiseta" required />
    </div>
    <div class="mb-3">
        <label asp-for="ShirtSize">Tamaño</label>
        <input type="text" class="form-control" asp-for="ShirtSize" placeholder="Tamaño de la Camiseta" required />
    </div>
    <div class="mb-3">
        <label asp-for="Price">Precio</label>
        <input type="number" class="form-control" asp-for="Price" placeholder="Precio de la Camiseta" required />
    </div>
    <div class="mb-3">
        <label asp-for="Type">Tipo</label>
        <input type="text" class="form-control" asp-for="Type" placeholder="Tipo de la Camiseta" required />
    </div>
    <div class="mb-3">
        <label asp-for="Material">Material</label>
        <input type="text" class="form-control" asp-for="Material" placeholder="Material de la Camiseta" />
    </div>
    <div class="mb-3">
        <label asp-for="Quantity">Cantidad</label>
        <input type="number" class="form-control" asp-for="Quantity" placeholder="Cantidad de Camisetas" required />
    </div>

    <button class="boton">Guardar</button>
    <button class="boton mb-3" asp-action="ShirtsList" asp-controller="Shirt">Regresar</button>
</form>

Creatisa/Views/Shirt/ShirtList.cshtml
@model List<ShirtModel>

@{
    ViewData["Title"] = "Listado de Camisetas";
    int Id = 0;
}
<link rel="stylesheet" href="~/css/views.css">

<div class="container-tablas">
    <div class="tabla-titul">
        <h1>Listado de Camisetas</h1>
        <a asp-controller="Shirt" asp-action="ShirtsAdd">+ Añadir</a>
    </div>

    <table class="tablass table table-borderless table-striped table-hover">
        <thead>
            <tr>
                <th scope="col">Acciones</th>
                <th scope="col">ID</th>
                <th scope="col">Nombre</th>
                <th scope="col">Color</th>
                <th scope="col">Tamaño</th>
                <th scope="col">Precio</th>
                <th scope="col">Tipo</th>
                <th scope="col">Material</th>
                <th scope="col">Cantidad</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var shirt in Model)
            {
                Id++;
                <tr>
                    <td>
                        <a class="btn" asp-controller="Shirt" asp-action="ShirtsEdit" asp-route-id="@shirt.Id">
                            <img class="editarr" src="~/imgadmin/edit.svg" alt="Editar">
                        </a>
                        <a class="btn" asp-controller="Shirt" asp-action="ShirtsDeleted" asp-route-id="@shirt.Id">
                            <img class="editarr" src="~/imgadmin/basura.svg" alt="Eliminar">
                        </a>
                    </td>
                    <td>@Id</td>
                    <td>@shirt.Name</td>
                    <td>@shirt.Color</td>
                    <td>@shirt.ShirtSize</td>
                    <td>@shirt.Price</td>
                    <td>@shirt.Type</td>
                    <td>@shirt.Material</td>
                    <td>@shirt.Quantity</td>
                </tr>
            }
        </tbody>
    </table>
</div>